### ISSUE TITLE
Esc no longer closes emote picker

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#190]

**Comment by rakslice** [comment]
It seems that there are problems navigating between the emote picker search, the grid, and the chat text input box generally; I'll look into this further at some point.

**Comment by ahjolinna** [comment]
for me the esc only closes the chat (the stable 1.6, on arch using Qt 5.9.1)

**Comment by alamminsalo** [comment]
Found a bug regarding this, the ctrl + wheel prevented clicking links and interacting with chat. Whoopsydaisy. Fixed with removing the mousearea and adding small floating zoom buttons

**Comment by rakslice** [comment]
Okay, so a couple of things:
- In Qt 5.9 / QtQuick 2.7, <kbd>Esc</kbd> key events do not happen by default but are available via `shortcutOverride`: https://doc.qt.io/qt-5/qml-qtquick-keys.html#shortcutOverride-signal
- Focus switching by toggling the `focus` parameter does not work consistently anymore.  I don't know of a solution to that yet.

**Comment by rakslice** [comment]
Okay, seems that using `.forceActiveFocus()` fixes the focus issue.
<kbd>Esc</kbd> is still not getting picked up in the GridView for some reason.
