### ISSUE TITLE
I keep getting seg faults recently.

### ISSUE THREAD

**Issue by mroNNorm** [alamminsalo/orion#50]
So for whatever reason recently I've gotten lots of seg faults. I believe it has to do with the chat but I'm not sure how to resovle the issue. I think it mostly happens with lots of chat spam. so when watching large streams I'll see it crash most often.
(I'm using Qt 5.8, dunno if you've tried it with 5.8 at all yet)

Here is the backtrace from gdb:
Thread 30 "QSGRenderThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff36ffd700 (LWP 17673)]
0x00007fffe4c13761 in ?? () from /usr/lib/libfreetype.so.6
(gdb) bt
#0  0x00007fffe4c13761 in ?? () from /usr/lib/libfreetype.so.6
#1  0x00007fffe4c58051 in ?? () from /usr/lib/libfreetype.so.6
#2  0x00007fffe4c2de5c in ?? () from /usr/lib/libfreetype.so.6
#3  0x00007fffe4c2eb6a in ?? () from /usr/lib/libfreetype.so.6
#4  0x00007fffe4c2fdf0 in ?? () from /usr/lib/libfreetype.so.6
#5  0x00007fffe4c153ae in FT_Load_Glyph () from /usr/lib/libfreetype.so.6
#6  0x00007fffe4c63099 in ?? () from /usr/lib/libfreetype.so.6
#7  0x00007fffe4c15585 in FT_Load_Glyph () from /usr/lib/libfreetype.so.6
#8  0x00007fffc3886469 in QFontEngineFT::loadGlyph(QFontEngineFT::QGlyphSet*, unsigned int, QFixed, QFontEngine::GlyphFormat, bool, bool) const ()
   from /usr/lib/libQt5XcbQpa.so.5
#9  0x00007fffc38890b1 in QFontEngineFT::loadGlyphFor(unsigned int, QFixed, QFontEngine::GlyphFormat, QTransform const&, bool, bool) () from /usr/lib/libQt5XcbQpa.so.5
#10 0x00007fffc388a9a9 in QFontEngineFT::alphaMapForGlyph(unsigned int, QFixed, QTransform const&) () from /usr/lib/libQt5XcbQpa.so.5
#11 0x00007fffc3882e4e in QFontEngineFT::alphaMapForGlyph(unsigned int, QFixed) () from /usr/lib/libQt5XcbQpa.so.5
#12 0x00007ffff0968f5f in QFontEngine::alphaMapForGlyph(unsigned int, QFixed, QTransform const&) () from /usr/lib/libQt5Gui.so.5
#13 0x00007fffc388ab1d in QFontEngineFT::alphaMapForGlyph(unsigned int, QFixed, QTransform const&) () from /usr/lib/libQt5XcbQpa.so.5
^ does that for a couple thousand times.

**Comment by mroNNorm** [comment]
So, I have tested it without chat, and it does seem like chat is the issue in this case. Might be people doing those weird ascii art things or other characters that are causing the issues.

**Comment by alamminsalo** [comment]
I found an issue with the chat message removal when queue was filled (500). I committed a fix, can you check if this solves the issue?

**Comment by mroNNorm** [comment]
Nope, still crashes. I sometimes get this crash pretty fast so I don't think it has to do with that.

**Comment by mroNNorm** [comment]
I'm starting to thinking it could be my fonts, seems to work fine on my laptop.

**Comment by alamminsalo** [comment]
The qfontengine issues make sense with the font issue. It could be that qt is having issues with the font you have as default. I think better would be to add some static font for the application to use, in this case a font with broad glyph support

**Comment by mroNNorm** [comment]
yeah, I see boxes on my laptop where it just seems to crash on my desktop. so something like that would probably solve the issue i'm seeing.

**Comment by ahjolinna** [comment]
@mroNNorm : you could try [debuging with strace](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Strace) to see if there are any missing libs/files that orion needs/trying to access...or other debugging method like [Valgrind](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Valgrind)

**Comment by mroNNorm** [comment]
open("/usr/share/fonts/TTF/AdobeBlank-Regular.ttf", O_RDONLY) = 123
with strace which the file is there, and valgrind just segfaults before the app actually starts for w/e reason

**Comment by mroNNorm** [comment]
@ahjolinna so I removed the google font and installed the adobe one and it seems to have fixed it form crashing. thanks

**Comment by alamminsalo** [comment]
Added default font (NotoSans), which has very broad character support. This should be now fixed, please review and close if the issue
